### ISSUE TITLE
page footer

### ISSUE THREAD

**Issue by xtof-durr** [jilljenn/tryalgo.org#15]
Bonjour Jill-Jênn, Clémence, Louis, et les autres,

deux choses décoratives. 

1. J'aimerais changer le pied de nos pages pour ne pas mettre en avant seulement Jill-Jênn Vie, moi-même et ENS Paris-Saclay. Est-ce qu'on pourrait juste y écrire un petit slogan ou "raise CornerCaseException" par exemple pour faire écho à "try algo" ? Ça vous irait?

2. Je vois que son mon smartphone (oui vous avez bien lu), dans nos pages les codes sont tronqués. Est-ce qu'il y a quelque chose qu'on puisse faire ou est-ce que important déjà? Ce n'est peut-être pas un site qu'on lit sur un tel appareil.

Je vais recommencer à être plus actif, maintenant que SWERC'2017 est terminé. 

xtof

**Comment by jilljenn** [comment]
Du coup c'est réglé youpi.
