### ISSUE TITLE
Reduce size of the sidebar / make the theme more adaptive

### ISSUE THREAD

**Issue by Naereen** [jilljenn/tryalgo.org#8]
Hi,

On a 1366-pixel large screen (and smaller) the sidebar is not displayed entirely with the default zoom level (100%).
Could you try to either make the theme more adaptive, or simply reduce the font of the sidebar, or reduce the zoom level of the whole website?

Here are two examples, first at 100%:
![tryalgo2](https://cloud.githubusercontent.com/assets/11994719/12810952/b12b7fd6-cb29-11e5-8bde-7a53f4241613.png)

Then at 80%:
![tryalgo1](https://cloud.githubusercontent.com/assets/11994719/12810947/acbff076-cb29-11e5-9275-739099fd1974.png)

**Comment by xtof-durr** [comment]
Je pense qu’il parle de ce type de débordement:



J’avais regardé une fois si on peut enlever le préfixe tryalgo, devant chaque module, mais pas trouvé.
Augmenter la taille de la marge me semble bien.
Il faut vérifier sur la taille d’un smartphone si ça passe.
Mais ce sont vraiment des détails.
Je me demande si un jour qn nous demande que tryalgo passe en python2.
Merci pour Notebook, c’est bien cool.

xtof

**Comment by Naereen** [comment]
C'est un mini-détail c'est vrai :art:.

Le site est très bien sinon, et en attendant, de ce que j'ai vu du bouquin, ça a l'air génial aussi.
J'ai hâte qu'il sorte en tout cas :open_mouth: !

**Comment by jilljenn** [comment]
Merci @Naereen, c'est vrai que ce thème n'est pas trop fait pour une longue description :/

Au fait, tu as vu [cette démo](http://nbviewer.jupyter.org/github/jilljenn/tryalgo/blob/master/examples/TryAlgo%20Maps%20in%20Paris.ipynb) ? :) Je vais l'ajouter au site.

**Comment by Naereen** [comment]
OK.
Sympa la démo !

**Comment by Naereen** [comment]
Le soucis d'affichage me semble encore là, ?

**Comment by xtof-durr** [comment]
C'est parcequ'on est trop lent à supprimer http://docs.tryalgo.org/
La documentation est en fait sur http://pythonhosted.org/tryalgo/ et là la mise en page est ok, non?

**Comment by Naereen** [comment]
Ah, oui, la doc est très bien (merci Sphinx), mais la [page d'accueil tryalgo.org](http://tryalgo.org/) est pas parfaite niveau "responsivité" (cf. exemples plus haut).

D'ailleurs, plutôt que de supprimer http://docs.tryalgo.org, ça pourrait juste être une redirection vers celle de pythonhosted?

**Comment by Naereen** [comment]
Bonjour,
@xtof-durr ce soucis de "responsiveness" ne me semble pas encore corrigé ?
A+

**Comment by xtof-durr** [comment]
Bonjour Lilan,

tu peux me montrer ce qui ne va pas? J'ai fait un tour et ça me paraît pas mal.

xtof

**Comment by Naereen** [comment]
Bonjour,
Vous aviez changé le thème du site principal, et depuis ça marche, mais la doc hébergée sur pythonhosted utilise un thème connu pour être non responsive.
![test sizzy co](https://user-images.githubusercontent.com/11994719/31622300-5fa70606-b29c-11e7-85f9-02ae62235b82.png)
(Cf. https://sizzy.co/?url=https%3A%2F%2Fpythonhosted.org%2Ftryalgo%2F pour plus d'exemple)

Une solution simple serait d'utiliser le thème [sphinx_rtd_theme](https://pypi.python.org/pypi/sphinx_rtd_theme) (par exemple)

**Comment by xtof-durr** [comment]
ah d'accord, on va changer de thème alors cette semaine. merci d'avoir insisté.
x

**Comment by Naereen** [comment]
OK.
Je sais que @jilljenn n'aime pas ce thème, vous arriverez à trouver un autre thème responsive si vous voulez. Je crois que ma liste [ici](http://perso.crans.org/besson/avoir.html#meilleur-theme) n'est pas vraiment à jour mais ça peut donner des pistes :smile: !

**Comment by jilljenn** [comment]
Bon finalement on a bien fait de changer de thème :D Merci Lilian !
